import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  reactStrictMode: true,
  // Content pages are statically generated by default (see generateStaticParams).
  // We do not force `output: "export"` so that adding server route handlers later
  // (LLM grading, auth, billing) stays frictionless.
  eslint: {
    // Linting is handled by Biome, not ESLint.
    ignoreDuringBuilds: true,
  },
  // The system catalog moved from /products to /systems; keep old links working.
  async redirects() {
    return [
      { source: "/products", destination: "/systems", permanent: true },
      { source: "/products/:slug", destination: "/systems/:slug", permanent: true },
    ];
  },
};

export default nextConfig;
